#
# Copyright (c) 2022 Darryl deHaan
# SPDX-License-Identifier: MIT
#

CONFIG_WS2812_STRIP=n
CONFIG_ZMK_RGB_UNDERGLOW=n
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n
CONFIG_ZMK_RGB_UNDERGLOW_ON_START=n
CONFIG_ZMK_RGB_UNDERGLOW_BRT_MAX=90

CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=n
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_USB=n
CONFIG_ZMK_RGB_UNDERGLOW_HUE_START=160
CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=3


#CONFIG_ZMK_HID_CONSUMER_REPORT_USAGES_BASIC=y


CONFIG_ZMK_HID_REPORT_TYPE_NKRO=n
